INHERIT: ./user-documentation/data/configs/path.yml

docs_dir: ./user-documentation/data/docs/path

site_name: PATh Documentation
site_url: "https://portal.path-cc.io/documentation/"
repo_name: osg-htc/user-documentation
theme:
  features:
    - navigation.tabs
    - content.tabs.link
  name: material
  logo: assets/PATh_Logo_Round_Color_White_Border.png
  favicon: assets/PATh_Logo_Round_Color.png
  custom_dir: overrides
extra:
  homepage: /

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/path.css
